import Head from 'next/head'
import Addbook from '../component/add-book'
import BookList from '../component/book-list'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Book App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
      <div style={{textAlign:"center"}}><h1>Book App</h1></div>
        <Addbook/>
        <BookList/>
      </main>
        
    </div>
  )
}
