import Head from 'next/head'
import BookList from '../component/book-list'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Book App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
      <h1>Book List</h1>
        <BookList/>
      </main>
        
    </div>
  )
}
